services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.offline
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
    command: deno task serve
    ports:
      - "8001:8000"
    networks:
      - offline-network
    depends_on:
      postgres:
        condition: service_healthy
  
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.offline
      target: migrator
      args:
        POSTGRES_HOST: ${POSTGRES_HOST}
    command: nessie migrate
    networks:
      - offline-network
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:17.2
    env_file:
      - ./apps/webapp/db.local.env
    ports:
      - "5432:5432"
    volumes:
      - trust_assembly_data_offline:/var/lib/postgresql/data
    networks:
      - offline-network
    healthcheck:
      test: ["CMD-SHELL", "runuser", "-u", "postgres", "--", "pg_isready"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 10s

volumes:
  trust_assembly_data_offline:
    driver: local

networks:
  offline-network:
    driver: bridge
    internal: false  # Set to true for completely offline operation