FROM denoland/deno:2.1.1 AS migrator

WORKDIR /migrate

ARG POSTGRES_HOST

ENV POSTGRES_USER=$POSTGRES_USER

COPY ./apps/webapp//api/nessie.config.ts .
COPY ./apps/webapp//api/db ./db

RUN deno install  --allow-read=${POSTGRES_HOST}:5432 --allow-write=nessie.config.ts,db -f  https://deno.land/x/nessie/cli.ts --global

FROM denoland/deno:2.1.1

WORKDIR /app

EXPOSE 5173

ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG POSTGRES_HOST

ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_HOST=$POSTGRES_HOST

COPY ./apps/webapp/ .

RUN deno install
