services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
    command: deno task serve
    ports:
      - "8001:8000"
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrator
      args:
        POSTGRES_HOST: ${POSTGRES_HOST}
    command: deno run -A https://deno.land/x/nessie/cli.ts migrate
